// <auto-generated />
using DS.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DS.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DS.Services.ProductAPI.Models.Dto.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Mobile",
                            Description = "Mobile",
                            ImageUrl = "C:\\Work\\Demo\\DSRestaurant\\DSRestaurant\\Images\\Mobile.jfif",
                            Price = 15.0,
                            ProductName = "Mobile"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Laptop",
                            Description = "Laptop",
                            ImageUrl = "C:\\Work\\Demo\\DSRestaurant\\DSRestaurant\\Images\\Laptop.jfif",
                            Price = 13.99,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Mobile",
                            Description = "Mobile",
                            ImageUrl = "C:\\Work\\Demo\\DSRestaurant\\DSRestaurant\\Images\\Mobile.jfif",
                            Price = 10.99,
                            ProductName = "Mobile"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Mobile",
                            Description = "Mobile",
                            ImageUrl = "C:\\Work\\Demo\\DSRestaurant\\DSRestaurant\\Images\\Mobile.jfif",
                            Price = 15.0,
                            ProductName = "Mobile"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
